# Generated by Django 5.1 on 2025-05-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Marca', models.CharField(max_length=300)),
                ('Precio', models.CharField(max_length=300)),
                ('Fecha', models.CharField(max_length=300)),
                ('Valor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='Ferremasito.productos')),
            ],
        ),
    ]
