# Generated by Django 5.1 on 2025-05-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremasito', '0002_categoria_producto_delete_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='Ferremasito.categoria'),
        ),
    ]
