# Generated by Django 5.1 on 2025-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremasito', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
